/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmesRouteImport } from './routes/filmes'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as FilmeIdRouteImport } from './routes/filme.$id'
import { Route as SerieIdRouteImport } from './routes/serie.$id'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesRoute = FilmesRouteImport.update({
  id: '/filmes',
  path: '/filmes',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmeIdRoute = FilmeIdRouteImport.update({
  id: '/filme/$id',
  path: '/filme/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieIdRoute = SerieIdRouteImport.update({
  id: '/serie/$id',
  path: '/serie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filmes': typeof FilmesRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRoute
  '/series': typeof SeriesRoute
  '/filme/$id': typeof FilmeIdRoute
  '/serie/$id': typeof SerieIdRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filmes': typeof FilmesRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRoute
  '/series': typeof SeriesRoute
  '/filme/$id': typeof FilmeIdRoute
  '/serie/$id': typeof SerieIdRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/filmes': typeof FilmesRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRoute
  '/series': typeof SeriesRoute
  '/filme/$id': typeof FilmeIdRoute
  '/serie/$id': typeof SerieIdRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/filmes'
    | '/live'
    | '/login'
    | '/player'
    | '/series'
    | '/filme/$id'
    | '/serie/$id'
    | '/api/public/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/filmes'
    | '/live'
    | '/login'
    | '/player'
    | '/series'
    | '/filme/$id'
    | '/serie/$id'
    | '/api/public/stream'
  id:
    | '__root__'
    | '/'
    | '/filmes'
    | '/live'
    | '/login'
    | '/player'
    | '/series'
    | '/filme/$id'
    | '/serie/$id'
    | '/api/public/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmesRoute: typeof FilmesRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  PlayerRoute: typeof PlayerRoute
  SeriesRoute: typeof SeriesRoute
  FilmeIdRoute: typeof FilmeIdRoute
  SerieIdRoute: typeof SerieIdRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes': {
      id: '/filmes'
      path: '/filmes'
      fullPath: '/filmes'
      preLoaderRoute: typeof FilmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filme/$id': {
      id: '/filme/$id'
      path: '/filme/$id'
      fullPath: '/filme/$id'
      preLoaderRoute: typeof FilmeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie/$id': {
      id: '/serie/$id'
      path: '/serie/$id'
      fullPath: '/serie/$id'
      preLoaderRoute: typeof SerieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmesRoute: FilmesRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  PlayerRoute: PlayerRoute,
  SeriesRoute: SeriesRoute,
  FilmeIdRoute: FilmeIdRoute,
  SerieIdRoute: SerieIdRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
